### ISSUE TITLE
import_path does not work with array of paths

### ISSUE THREAD

**Issue by sconno05** [appleboy/gulp-compass#101]
The documentation states that the import_path option can take a string or an array.  If you pass an array, only the first item in the list is considered.

For example, with this specification, no files can be imported from other_sass.

```
gulp.task('sass', function() {
    gulp.src(path.SASS)
        .pipe(compass({
            css: path.DEST,
            sass: path.SASS_FOLDER,
            import_path: [                
                "../../../sass",
                "../../other_sass"
            ],
            require:[
                "bootstrap-sass",
                "font-awesome-sass"
            ]
       }))
       .on('error', logError)
   .pipe(gulp.dest(path.DEST));
});
```

**Comment by sconno05** [comment]
I forked the repository and discovered that this is indeed supported (with a unit test to boot).  I retried and got it working, I must have had a typo.

**Comment by appleboy** [comment]
@sconno05 Nice :+1:
