### ISSUE TITLE
Errno::EACCES on line ["245"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /css

### ISSUE THREAD

**Issue by cssgdhd** [appleboy/gulp-compass#104]
I got a similart error ` Errno::EACCES on line ["245"] of /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb: Permission denied - /css` while I was using `gulp.start('task')` to compile my `sass` file on the node.js serverside.But when I run `gulp` from the terminal,it works well.Could someone help me to solve the problem?

**Comment by appleboy** [comment]
Why use `gulp.start`? Could you post your gulp config file?

**Comment by cssgdhd** [comment]
I didn't want to use `gulp` from the CLI ,I just want to use it directly from node server.Anyway,I had found another way to do the things I want.
