### ISSUE TITLE
Does this work w/Compass' Recent Source Map Support?

### ISSUE THREAD

**Issue by grayghostvisuals** [appleboy/gulp-compass#24]
We are making an in-house App at work to try shiny new stuff. My question is the following:

We want to use the Source Maps implementation in `compass --pre` [https://github.com/chriseppstein/compass/issues/1108#issuecomment-30285540](https://github.com/chriseppstein/compass/issues/1108#issuecomment-30285540) and wonder if this gulp plugin will work with it? Want to make sure before going forward with the entire setup and avoid discovering we are up a river w/out a paddle so to speak. Thanks!

cc:@dustinhorton

**Comment by Ziggizag** [comment]
I use gulp-compass@2.1.0 and no way - while transpililig SCSS file - sourcemap is not being generated, while it's so while using plain compass watcher.

This is my gulp:

gulp.task('compass', function() {
    return gulp.src('app/sass/styles.scss')
    .pipe(plumber())
    .pipe(compass({
    	project: path.join(__dirname),
		css: 'app/stylesheets',
		sass: 'app/sass',
		font: 'app/fonts',
		image: 'app/images',
		require: [
			'bootstrap-sass',
			'compass/import-once/activate'
		],
		sourcemap: true,
		debug: true
    }))
    .on('error', function(error) {
		console.log(error);
		this.emit('end');
    })
    .pipe(plumber.stop())
	.pipe(gulp.dest('app/stylesheets'));
});

This is so nasty as missing sourcemap is such a serious issue for a developer!!!

**Comment by Ziggizag** [comment]
Strange!!!

I have installed autoprefixer and prolem seems to be gone!

**Comment by resting** [comment]
Hi Guys, here's my gulpfile.

```
gulp.task('css',function () {
    return gulp.src('sass/style.scss')
        .pipe(compass({
            sourcemap:true,
            debug:true,
            config_file:'./config.rb',
            css: './',
            sass:'sass'
        }))
        .pipe(postcss([autoprefixer({browsers: ['last 2 versions']})]))
        .pipe(gulp.dest(''))
});
```

I have `sourcemap = true` in my `config.rb`.

style.css.map is generated, but it's not loaded in the generated `style.css`. Is there something I'm missing?

**Comment by grayghostvisuals** [comment]
Compass has be deprecated in favor of eyeglass. It would be best if you don't use Compass anymore and go with another option like autoprefixer and LibSass.
