### ISSUE TITLE
Allowing compass to run in watch mode

### ISSUE THREAD

**Issue by svallory** [appleboy/gulp-compass#27]
Hi, I just pushed an experimental version [here](/theblacksmith/gulp-compass) which allows the use of 'watch' option.

I'm currently using it like this...

```javascript
    gulp
      .src('app/styles/**/*.scss')
      .pipe(
        compass({
          project: __dirname,
          watch: true,
          css: 'assets/css/modules',
          sass: 'app/styles/modules',
          image: 'assets/img',
          import_path: [
              'app/components', 
              'app/styles', 
              'app/styles/modules', 
              'app/styles/modules/' + MODULE
          ],
          require: ['compass']
        })
      );

    // livereload css
    gulp.src('assets/css/**/*.css')
      .pipe(watch())
      .pipe(livereload());
```

It seems to work well but the `gulp.src(paths[MODULE].sass)` shouldn't be required.

So... two things.

1. Is there a better way to make the compile method run?
2. Do you guys want gulp-compass to go this way? If so, I can make a pull request.

Btw, I bumped the version there to 1.1.6.

**Comment by appleboy** [comment]
Please download v2.0.4
