### ISSUE TITLE
http_generated_images_path

### ISSUE THREAD

**Issue by ArtemMedvedev** [appleboy/gulp-compass#89]
Please add an option in the configuration  http_generated_images_path. 
This really is not enough, without this line I get the wrong path in the generated CSS file.
I need use a config.rb to use this option.
While I found a solution I understand that this is a global problem.

Best regards,
Artem Medvedev

**Comment by mouhsinelonly** [comment]
+million

**Comment by appleboy** [comment]
I will take it on `compass 1.0.3`

**Comment by appleboy** [comment]
@mouhsinelonly @ArtemMedvedev Please refer [generated_images_path](https://github.com/appleboy/gulp-compass#generated_images_path) option.

**Comment by ArtemMedvedev** [comment]
@appleboy thank`s  lot, works well!
