### ISSUE TITLE
Globbing?

### ISSUE THREAD

**Issue by dallasbpeters** [appleboy/gulp-compass#90]
Curious if anyone has successfully been globbing files? `@import "modules/*";` I can't seem to get it to work with gulp-compass

**Comment by appleboy** [comment]
@dallasbpeters  Please try [sass-globbing](http://fuseinteractive.ca/blog/automatic-sass-imports-sass-globbing)

**Comment by appleboy** [comment]
@dallasbpeters I create unit test for importing globbing files.

Please see [compass_test.js#L287-L301](https://github.com/appleboy/gulp-compass/blob/master/test/compass_test.js#L287-L301) and [config.rb#1](https://github.com/appleboy/gulp-compass/blob/master/test/config.rb#L1).
