### ISSUE TITLE
Compass fails since upgrade to Yosemite

### ISSUE THREAD

**Issue by christophrumpel** [appleboy/gulp-compass#91]
Hey,

since I updated to Yosemite my Gulp tasks are not working anymore and I get this error:

    [17:12:52] Starting 'styles'...
    [17:12:52] Finished 'styles' after 9.56 ms
    [17:12:52] LoadError on line ["121"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:     cannot load such file -- breakpoint
    Run with --trace to see the full backtrace

    [17:12:52] gulp-notify: [Sass Error] Error: Compass failed

I have uninstalled compass and sass and reinstalled them with gem. I also reinstalled XCode but nothing helped. Does this package has a problem since Yosemite?

Versions:
Mac OSX Yosemite

Gulp 3.8.10
Gulp local 3.8.10

Sass 3.4.9
Compass 1.0.1
Ruby 2.1.5p273

Thx and cheers 
Christoph

**Comment by dotnetCarpenter** [comment]
I have gulp-compass running on Yosemite. Other than that, I can only say that this looks to be a compass error. What happens if you run `compass compile` in the terminal (in your project)?

**Comment by christophrumpel** [comment]
Hey,

thx. When I run this command, I get the same error =(

    LoadError on line ["121"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- breakpoint
Run with --trace to see the full backtrace

**Comment by dotnetCarpenter** [comment]
Well, that's it. Fix the compass error and gulp-compass will work. I've have personally never encountered such error, so I can't provide much help.

**Comment by christophrumpel** [comment]
Hey, yeah you are right, that was the problem. Needed to reinstall all of Ruby, Sass, Compass. But now it is working again.
Thx.
